- hosts: localhost
  tasks:
    # - name: install packages
    #   become: true
    #   become_user: root
    #   apt:
    #     state: present
    #     name:
    #       - htop
    #       - neofetch
    #       - fonts-powerline
    #       - snapd
    #       - unzip

    - name: Download Nerd Font
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip
        dest: ~/ansible-setup/tmp/Hack.zip
        # mode: 0755

    - name: Unzip the Hack Font
      shell: unzip Hack.zip
      args:
        chdir: ~/ansible-setup/tmp/

    - name: Copy Hack Font to Font Folder
      copy:
        src: ~/ansible-setup/tmp/Hack Regular Nerd Font Complete Mono.ttf
        dest: ~/.local/share/fonts/

    - name: Remove Temp
      file:
        path: ~/ansible-setup/tmp/
        state: absent

    # - name: Install zsh
    #   ansible.builtin.package:
    #     name: zsh
    #     state: latest
    #   become: yes

    # - name: Install oh my zsh
    #   git:
    #     repo: https://github.com/ohmyzsh/ohmyzsh.git
    #     dest: ~/.oh-my-zsh
    #     depth: 1

    # - name: Copy zshrc
    #   copy:
    #     src: files/zsh/zshrc
    #     dest: ~/.zshrc

    # - name: Backup bashrc
    #   copy:
    #     src: ~/.bashrc
    #     dest: ~/.bashrc.bak

    # - name: Copy bashrc
    #   copy:
    #     src: files/bash/bashrc
    #     dest: ~/.bashrc

    # - name: Install starship package
    #   community.general.snap:
    #     name: starship
    #   become: yes

    # - name: Create config directory
    #   file:
    #     path: ~/.config/starship
    #     state: directory

    # - name: Copy config file
    #   copy:
    #     src: config/starship/starship.toml
    #     dest: ~/.config/starship/starship.toml
