- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - htop
          - neofetch
          - exa
          - fonts-powerline
          - snapd
          - unzip

    - name: Creates TMP directory
      file:
        path: ~/ansible-setup/tmp
        state: directory

    - name: Download Nerd Font
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip
        dest: ~/ansible-setup/tmp/Hack.zip
        # mode: 0755

    - name: Unzip the Hack Font
      shell: unzip Hack.zip
      args:
        chdir: ~/ansible-setup/tmp/

    - name: Remove License file
      file:
        path: ~/ansible-setup/tmp/LICENSE.md
        state: absent
    - name: Remove Readme files
      file:
        path: ~/ansible-setup/tmp/readme.md
        state: absent

    - name: Remove Zip files
      file:
        path: ~/ansible-setup/tmp/Hack.zip
        state: absent

    - name: Copy Hack Font to Font Folder
      copy:
        src: ~/ansible-setup/tmp/
        dest: ~/.fonts/

    - name: Remove Temp DIR
      file:
        path: ~/ansible-setup/tmp/
        state: absent

    - name: Install zsh
      ansible.builtin.package:
        name: zsh
        state: latest
      become: yes

    - name: Install oh my zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        depth: 1

    - name: Copy zshrc
      copy:
        src: files/zsh/zshrc
        dest: ~/.zshrc

    - name: Creates .ZSH directory
      file:
        path: ~/.zsh/
        state: directory

    - name: Copy ZSH Configs
      copy:
        src: zsh/config/
        dest: ~/.zsh/

    - name: Backup bashrc
      copy:
        src: ~/.bashrc
        dest: ~/.bashrc.bak

    - name: Copy bashrc
      copy:
        src: files/bash/bashrc
        dest: ~/.bashrc

    - name: Install starship package
      community.general.snap:
        name: starship
      become: yes

    - name: Create config directory
      file:
        path: ~/.config/
        state: directory

    - name: Copy config file
      copy:
        src: config/starship/starship.toml
        dest: ~/.config/starship.toml
