- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - tcsh
          - htop
          - neofetch
          - fonts-powerline
          - snap

    - name: Install zsh
      ansible.builtin.package:
        name: zsh
        state: latest
      become: yes

    - name: Install oh my zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        depth: 1

    - name: Copy zshrc
      copy:
        src: files/zsh/zshrc
        dest: ~/.zshrc

    - name: Install zsh-syntax-highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Install zsh-autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Install zsh-completions plugin
      git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-completions

    - name: Install git-fuzzy plugin
      git:
        repo: https://github.com/bigH/git-fuzzy.git
        dest: ~/.oh-my-zsh/custom/plugins/git-fuzzy

    - name: Install fzf-tab plugin
      git:
        repo: https://github.com/Aloxaf/fzf-tab
        dest: ~/.oh-my-zsh/custom/plugins/fzf-tab

    - name: Install starship package
      snap:
        name: starship
        state: latest
      become: yes

    - name: Create config directory
      file:
        path: ~/.config/starship
        state: directory

    - name: Copy config file
      copy:
        src: config/starship/config.toml
        dest: ~/.config/starship/config.toml
